default_install_hook_types: [pre-commit]
fail_fast: true

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer

  - repo: local
    hooks:
      - id: ruff-format-check
        name: ruff format --check
        entry: poetry run ruff format --check .
        language: system
        pass_filenames: false

      - id: ruff-check
        name: ruff check
        entry: poetry run ruff check .
        language: system
        pass_filenames: false

      - id: pytest
        name: pytest
        entry: poetry run pytest
        language: system
        pass_filenames: false
